package com.techsajib.chinesehelper.HSK4;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.os.Bundle;
import android.widget.ListView;

import com.techsajib.chinesehelper.HSK3.HSK3Adapter;
import com.techsajib.chinesehelper.HSK3.HSK3Model;
import com.techsajib.chinesehelper.R;

import java.util.ArrayList;

public class HSK4Listview extends AppCompatActivity {

    ListView listView;
    HSK4Adapter hsk4Adapter;
    ArrayList<HSK4Model> item = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.hsk4_listview);

        // for HSK1 Toolbar settings here
        Toolbar toolbar = findViewById(R.id.hsk4_toolbar);
        setSupportActionBar(toolbar);

        // for back button
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);

        //for listview section
        listView = findViewById(R.id.hsk4ListView);

        //CREATING DATA FOR LISTVIEW
        //A category
        item.add(new HSK4Model("爱情","àiqíng","love, romance"));
        item.add(new HSK4Model("安排","ānpái","arrangement, set up"));
        item.add(new HSK4Model("安全","ānquán","secure, safe, security, safety"));
        item.add(new HSK4Model("按时","ànshí","on time, before deadline, on schedule"));
        item.add(new HSK4Model("按照","ànzhào","according to, on the basis of"));
        //B category
        item.add(new HSK4Model("百分之","bǎifēnzhī","percent"));
        item.add(new HSK4Model("棒","bàng","smart, capable, strong, stick"));
        item.add(new HSK4Model("包子","bāozi","bun, steamed stuffed bun"));
        item.add(new HSK4Model("保护","bǎohù","protect, safeguard"));
        item.add(new HSK4Model("保证","bǎozhèng","ensure, guarantee"));
        item.add(new HSK4Model("报名","bàomíng","sign up, register"));
        item.add(new HSK4Model("抱","bào","hold, adopt"));
        item.add(new HSK4Model("抱歉","bàoqiàn","feel sorry, feel regret, apologize"));
        item.add(new HSK4Model("倍","bèi","times, double, twice as much"));
        item.add(new HSK4Model("本来","běnlái","originally"));
        item.add(new HSK4Model("笨","bèn","stupid, foolish, silly"));
        item.add(new HSK4Model("比如","bǐrú","such as, for example"));
        item.add(new HSK4Model("毕业","bìyè","graduation"));
        item.add(new HSK4Model("遍","biàn","all over, everywhere"));
        item.add(new HSK4Model("标准","biāozhǔn","standard"));
        item.add(new HSK4Model("表格","biǎogé","form"));
        item.add(new HSK4Model("表示","biǎoshì","express, show, represent"));
        item.add(new HSK4Model("表演","biǎoyǎn","perform, exhibition, play"));
        item.add(new HSK4Model("表扬","biǎoyáng","praise"));
        item.add(new HSK4Model("饼干","bǐnggān","biscuit, cookie"));
        item.add(new HSK4Model("并且","bìngqiě","also, and, moreover, furthermore"));
        item.add(new HSK4Model("博士","bóshì","Ph.D, doctor of philosophy"));
        item.add(new HSK4Model("不过","búguò","only, however, anyway"));
        item.add(new HSK4Model("不得不","bùdébù","have to, can't avoid, have no choice or option"));
        item.add(new HSK4Model("不管","bùguǎn","no matter, regardless of"));
        item.add(new HSK4Model("不仅","bùjǐn","not only"));
        item.add(new HSK4Model("部分","bùfen","part, share, section"));
        //C category
        item.add(new HSK4Model("擦","cā","rub, wipe, erase"));
        item.add(new HSK4Model("猜","cāi","to guess"));
        item.add(new HSK4Model("材料","cáiliào","material"));
        item.add(new HSK4Model("参观","cānguān","visit, to look around"));
        item.add(new HSK4Model("餐厅","cāntīng","restaurant, dining hall"));
        item.add(new HSK4Model("厕所","cèsuǒ","toilet, washroom"));
        item.add(new HSK4Model("差不多","chàbùduō","almost, nearly"));
        item.add(new HSK4Model("尝","cháng","taste, flavor"));
        item.add(new HSK4Model("长城","chángchéng","the Great Wall"));
        item.add(new HSK4Model("长江","chángjiāng","yangtze river"));
        item.add(new HSK4Model("场","chǎng","large place used for a specific purpose"));
        item.add(new HSK4Model("超过","chāoguò","to surpass, to exceed, to outstrip"));
        item.add(new HSK4Model("乘坐","chéngzuò","to ride (in a vehicle)"));
        item.add(new HSK4Model("成功","chénggōng","success"));
        item.add(new HSK4Model("成为","chéngwéi","become"));
        item.add(new HSK4Model("诚实","chéngshí","honest, truthful"));
        item.add(new HSK4Model("吃惊","chījīng","to be amazed, to be shocked"));
        item.add(new HSK4Model("重新","chóngxīn","again, once more"));
        item.add(new HSK4Model("抽烟","chōuyān","to smoke (a cigarette, tobacco)"));
        item.add(new HSK4Model("出差","chūchāi","to go on an official or business trip"));
        item.add(new HSK4Model("出发","chūfā","to start out, to set off"));
        item.add(new HSK4Model("出生","chūshēng","born, birth"));
        item.add(new HSK4Model("出现","chūxiàn","appear, arise, show up"));
        item.add(new HSK4Model("厨房","chúfáng","kitchen"));
        item.add(new HSK4Model("传真","chuánzhēn","fax"));
        item.add(new HSK4Model("窗户","chuānghu","window"));
        item.add(new HSK4Model("词语","cíyǔ","terms, words"));
        item.add(new HSK4Model("从来","cónglái","always"));
        item.add(new HSK4Model("粗心","cūxīn","careless"));
        item.add(new HSK4Model("存","cún","exist, deposit, store, keep, survive"));
        item.add(new HSK4Model("错误","cuò wù","error, mistake"));
        //D category
        item.add(new HSK4Model("答案","dá'àn","answer, solution"));
        item.add(new HSK4Model("打扮","dǎban","dress up, make up"));
        item.add(new HSK4Model("打扰","dǎrǎo","disturb, bother, trouble"));
        item.add(new HSK4Model("打印","dǎyìn","print"));
        item.add(new HSK4Model("打招呼","dǎzhāohū","to give prior notice"));
        item.add(new HSK4Model("打折","dǎzhé","to give a discount"));
        item.add(new HSK4Model("打针","dǎzhēn","to give or have an injection"));
        item.add(new HSK4Model("大概","dàgài","probably, roughly"));
        item.add(new HSK4Model("大使馆","dàshǐguǎn","embassy"));
        item.add(new HSK4Model("大约","dàyuē","about, approximately"));
        item.add(new HSK4Model("大夫","dàifu","doctor"));
        item.add(new HSK4Model("戴","dài","to put on or wear (glasses, hat, gloves etc)"));
        item.add(new HSK4Model("当","dāng","when, during"));
        item.add(new HSK4Model("当时","dāngshí","at that time"));
        item.add(new HSK4Model("刀","dāo","knife"));
        item.add(new HSK4Model("导游","dǎoyóu","tourist guide, guidebook"));
        item.add(new HSK4Model("倒","dào","to move backwards, converse"));
        item.add(new HSK4Model("到处","dàochù","everywhere, in all places"));
        item.add(new HSK4Model("到底","dàodǐ","finally, in the end, after all"));
        item.add(new HSK4Model("道歉","dàoqiàn","apologize"));
        item.add(new HSK4Model("得","dé","particle used to express capability, possibility, degree, effect etc"));
        item.add(new HSK4Model("得意","déyì","proud"));
        item.add(new HSK4Model("登机牌","dēng jī pái","boarding pass"));
        item.add(new HSK4Model("等","děng","wait (verb)"));
        item.add(new HSK4Model("低","dī","low, beneath"));
        item.add(new HSK4Model("底","dǐ","bottom, base, background"));
        item.add(new HSK4Model("地点","dìdiǎn","location, place, venue"));
        item.add(new HSK4Model("地球","dìqiú","earth, planet"));
        item.add(new HSK4Model("地址","dìzhǐ","address"));
        item.add(new HSK4Model("掉","diào","fall, drop, lose, come off"));
        item.add(new HSK4Model("调查","diàochá","investigation, inquiry, survey"));
        item.add(new HSK4Model("丢","diū","throw, put aside"));
        item.add(new HSK4Model("动作","dòngzuò","action, movement"));
        item.add(new HSK4Model("堵车","dǔchē","traffic jam"));
        item.add(new HSK4Model("肚子","dùzi","belly, stomach"));
        item.add(new HSK4Model("短信","duǎnxìn","SMS"));
        item.add(new HSK4Model("对话","duìhuà","dialogue"));
        item.add(new HSK4Model("对面","duìmiàn","opposite"));
        item.add(new HSK4Model("对于","duìyú","regarding, As far as is concerned"));
        //E category
        item.add(new HSK4Model("儿童","értóng","children"));
        item.add(new HSK4Model("而","ér","and, as well as"));
        //F category
        item.add(new HSK4Model("发生","fāshēng","happen, occur, break out"));
        item.add(new HSK4Model("发展","fāzhǎn","development, growth"));
        item.add(new HSK4Model("法律","fǎlǜ","law"));
        item.add(new HSK4Model("翻译","fānyì","translate, interpreter"));
        item.add(new HSK4Model("烦恼","fánnǎo","annoyance, vexation"));
        item.add(new HSK4Model("反对","fǎnduì","opposition"));
        item.add(new HSK4Model("方法","fāngfǎ","method, way, means"));
        item.add(new HSK4Model("方面","fāngmiàn","aspect, respect"));
        item.add(new HSK4Model("方向","fāngxiàng","direction, orientation"));
        item.add(new HSK4Model("房东","fángdōng","landlord"));
        item.add(new HSK4Model("放弃","fàngqì","give up, abandon"));
        item.add(new HSK4Model("放暑假","fàngshǔjià","summer vacation"));
        item.add(new HSK4Model("放松","fàngsōng","relax"));
        item.add(new HSK4Model("份","fèn","part, share, copy"));
        item.add(new HSK4Model("丰富","fēngfù","rich"));
        item.add(new HSK4Model("否则","fǒuzé","otherwise"));
        item.add(new HSK4Model("符合","fúhé","in keeping with, in accordance with"));
        item.add(new HSK4Model("付款","fùkuǎn","payment"));
        item.add(new HSK4Model("复印","fùyìn","photocopy"));
        item.add(new HSK4Model("复杂","fùzá","complicated"));
        item.add(new HSK4Model("富","fù","rich, surname Fu"));
        item.add(new HSK4Model("父亲","fùqīn","father"));
        item.add(new HSK4Model("负责","fùzé","to take responsibility"));
        //G category
        item.add(new HSK4Model("改变","gǎibiàn","change, transform"));
        item.add(new HSK4Model("干杯","gānbēi","cheers"));
        item.add(new HSK4Model("感动","gǎndòng","to move, moving"));
        item.add(new HSK4Model("感觉","gǎnjué","feel, perception, sense"));
        item.add(new HSK4Model("感情","gǎnqíng","feeling, emotion, sensation"));
        item.add(new HSK4Model("感谢","gǎnxiè","gratitude, grateful, thankful"));
        item.add(new HSK4Model("敢","gǎn","daring"));
        item.add(new HSK4Model("赶","gǎn","rush, hurry, to catch up"));
        item.add(new HSK4Model("干","gàn","to do (some work)"));
        item.add(new HSK4Model("刚","gāng","just, exactly, hard, strong"));
        item.add(new HSK4Model("高速公路","gāosù gōnglù","expressway, highway"));
        item.add(new HSK4Model("胳膊","gēbó","arm"));
        item.add(new HSK4Model("各","gè","each, every"));
        item.add(new HSK4Model("公里","gōnglǐ","kilometer"));
        item.add(new HSK4Model("功夫","gōngfū","skill, effort, art, kung fu"));
        item.add(new HSK4Model("工资","gōngzī","wage, pay"));
        item.add(new HSK4Model("共同","gòngtóng","common, join, together"));
        item.add(new HSK4Model("够","gòu","to reach, to be enough"));
        item.add(new HSK4Model("购物","gòuwù","shopping"));
        item.add(new HSK4Model("估计","gūjì","estimate"));
        item.add(new HSK4Model("鼓励","gǔlì","encourage"));
        item.add(new HSK4Model("故意","gùyì","deliberately, on purpose"));
        item.add(new HSK4Model("顾客","gùkè","customer, client"));
        item.add(new HSK4Model("挂","guà","suspend, hang"));
        item.add(new HSK4Model("关键","guānjiàn","key, crucial point, crux"));
        item.add(new HSK4Model("观众","guānzhòng","audience, spectators"));
        item.add(new HSK4Model("管理","guǎnlǐ","administration, management"));
        item.add(new HSK4Model("光","guāng","light, bright"));
        item.add(new HSK4Model("广播","guǎngbō","radio broadcast, widely spread"));
        item.add(new HSK4Model("广告","guǎnggào","advertisement"));
        item.add(new HSK4Model("逛","guàng","to stroll, to visit"));
        item.add(new HSK4Model("规定","guīdìng","rule, regulation"));
        item.add(new HSK4Model("国籍","guójí","nationality, country of citizenship"));
        item.add(new HSK4Model("国际","guójì","international"));
        item.add(new HSK4Model("果汁","guǒzhī","fruit juice"));
        item.add(new HSK4Model("过程","guòchéng","course of events, process"));
        //H category
        item.add(new HSK4Model("海洋","hǎiyáng","ocean"));
        item.add(new HSK4Model("害羞","hàixiū","shy"));
        item.add(new HSK4Model("寒假","hánjià","winter vacation"));
        item.add(new HSK4Model("汗","hàn","sweat, perspiration"));
        item.add(new HSK4Model("航班","hángbān","flight"));
        item.add(new HSK4Model("好处","hǎochù","benefit"));
        item.add(new HSK4Model("好像","hǎoxiàng","as if, to seem like"));
        item.add(new HSK4Model("号码","hàomǎ","number"));
        item.add(new HSK4Model("合格","hégé","qualified, eligible"));
        item.add(new HSK4Model("合适","héshì","appropriate, suitable"));
        item.add(new HSK4Model("盒子","hézi","box"));
        item.add(new HSK4Model("厚","hòu","thick"));
        item.add(new HSK4Model("后悔","hòuhuǐ","regret, repent"));
        item.add(new HSK4Model("互联网","mùliánwǎng","internet"));
        item.add(new HSK4Model("互相","hùxiāng","each other, mutual"));
        item.add(new HSK4Model("护士","hùshi","nurse"));
        item.add(new HSK4Model("怀疑","huáiyí","doubt, suspect"));
        item.add(new HSK4Model("回忆","huíyì","memories, recollection"));
        item.add(new HSK4Model("活动","huódòng","activity"));
        item.add(new HSK4Model("活泼","huópō","lively, active"));
        item.add(new HSK4Model("火","huǒ","fire"));
        item.add(new HSK4Model("获得","huòdé","get, receive"));
        //J category
        item.add(new HSK4Model("基础","jīchǔ","foundation, base"));
        item.add(new HSK4Model("激动","jīdòng","excited, agitate"));
        item.add(new HSK4Model("积极","jījí","energetic, proactive, positive"));
        item.add(new HSK4Model("积累","jīlěi","accumulation"));
        item.add(new HSK4Model("即使","jíshǐ","even if"));
        item.add(new HSK4Model("及时","jíshí","timely, without delay"));
        item.add(new HSK4Model("寄","jì","to mail, to send"));
        item.add(new HSK4Model("技术","jìshù","technology"));
        item.add(new HSK4Model("既然","jìrán","since, as, although"));
        item.add(new HSK4Model("继续","jìxù","continue"));
        item.add(new HSK4Model("计划","jìhuà","plan"));
        item.add(new HSK4Model("记者","jìzhě","reporter, journalist"));
        item.add(new HSK4Model("加班","jiābān","overtime work"));
        item.add(new HSK4Model("加油站","jiāyóuzhàn","gas station"));
        item.add(new HSK4Model("家具","jiājù","furniture"));
        item.add(new HSK4Model("假","jiǎ","fake, false"));
        item.add(new HSK4Model("价格","jiàgé","price"));
        item.add(new HSK4Model("坚持","jiānchí","to insist on, to continue upholding"));
        item.add(new HSK4Model("减肥","jiǎnféi","to lose weight"));
        item.add(new HSK4Model("减少","jiǎnshǎo","reduce, decrease"));
        item.add(new HSK4Model("建议","jiànyì","suggest, recommend, proposal"));
        item.add(new HSK4Model("将来","jiānglái","future"));
        item.add(new HSK4Model("奖金","jiǎngjīn","bonus, award money"));
        item.add(new HSK4Model("降低","jiàngdī","to bring down"));
        item.add(new HSK4Model("降落","jiàngluò","landing, descent"));
        item.add(new HSK4Model("交","jiāo","hand over"));
        item.add(new HSK4Model("交流","jiāoliú","communication"));
        item.add(new HSK4Model("交通","jiāotōng","traffic"));
        item.add(new HSK4Model("郊区","jiāoqū","suburbs, outskirts"));
        item.add(new HSK4Model("骄傲","jiāo'ào","proud"));
        item.add(new HSK4Model("饺子","jiǎozi","dumpling"));
        item.add(new HSK4Model("教授","jiàoshòu","professor"));
        item.add(new HSK4Model("教育","jiàoyù","education"));
        item.add(new HSK4Model("接受","jiēshòu","accept"));
        item.add(new HSK4Model("接着","jiēzhe","then, to carry on"));
        item.add(new HSK4Model("结果","jiéguǒ","result, outcome"));
        item.add(new HSK4Model("节","jié","festival, holiday"));
        item.add(new HSK4Model("节约","jiéyuē","saving"));
        item.add(new HSK4Model("解释","jiěshì","explanation"));
        item.add(new HSK4Model("尽管","jǐnguǎn","although, despite"));
        item.add(new HSK4Model("紧张","jǐnzhāng","nervous"));
        item.add(new HSK4Model("禁止","jìnzhǐ","prohibit, forbid"));
        item.add(new HSK4Model("进行","jìnxíng","in progress"));
        item.add(new HSK4Model("京剧","jīngjù","beijing opera"));
        item.add(new HSK4Model("精彩","jīngcǎi","marvellous, brilliant"));
        item.add(new HSK4Model("经济","jīngjì","economic"));
        item.add(new HSK4Model("经历","jīnglì","experience"));
        item.add(new HSK4Model("经验","jīngyàn","experience"));
        item.add(new HSK4Model("景色","jǐngsè","view, scenery"));
        item.add(new HSK4Model("警察","jǐngchá","policeman"));
        item.add(new HSK4Model("竞争","jìngzhēng","competition"));
        item.add(new HSK4Model("竟然","jìngrán","unexpectedly"));
        item.add(new HSK4Model("镜子","jìngzi","mirror"));
        item.add(new HSK4Model("究竟","jiūjìng","after all, actually"));
        item.add(new HSK4Model("举","jǔ","lift, to hold up, to raise"));
        item.add(new HSK4Model("举办","jǔbàn","to conduct, to hold"));
        item.add(new HSK4Model("举行","jǔxíng","to hold (a meeting, ceremony etc)"));
        item.add(new HSK4Model("拒绝","jùjué","refuse, decline, reject"));
        item.add(new HSK4Model("聚会","jùhuì","get together"));
        item.add(new HSK4Model("距离","jùlí","distance"));
        //K category
        item.add(new HSK4Model("开玩笑","kāiwánxiào","just kidding, to make fun"));
        item.add(new HSK4Model("开心","kāixīn","to feel happy, to have a great time"));
        item.add(new HSK4Model("看法","kànfǎ","view"));
        item.add(new HSK4Model("烤鸭","kǎoyā","roast duck"));
        item.add(new HSK4Model("考虑","kǎolǜ","consideration"));
        item.add(new HSK4Model("棵","kē","classifier for trees"));
        item.add(new HSK4Model("科学","kēxué","science"));
        item.add(new HSK4Model("咳嗽","késou","cough"));
        item.add(new HSK4Model("可怜","kělián","pathetic, pitiful"));
        item.add(new HSK4Model("可是","kěshì","however, but"));
        item.add(new HSK4Model("可惜","kěxī","unfortunately"));
        item.add(new HSK4Model("客厅","kètīng","living room"));
        item.add(new HSK4Model("肯定","kěndìng","to be sure, to be certain"));
        item.add(new HSK4Model("空","kōng","leisure, free time, to empty"));
        item.add(new HSK4Model("空气","kōngqì","air"));
        item.add(new HSK4Model("恐怕","kǒngpà","I'm afraid, to fear"));
        item.add(new HSK4Model("苦","kǔ","bitter, pain, to suffer"));
        item.add(new HSK4Model("矿泉水","kuàngquán shuǐ","mineral water"));
        item.add(new HSK4Model("困","kùn","sleepy"));
        item.add(new HSK4Model("困难","kùnnan","difficulty, problem, issue"));
        //L category
        item.add(new HSK4Model("垃圾桶","lājītǒng","trash, rubbish bin"));
        item.add(new HSK4Model("拉","lā","pull"));
        item.add(new HSK4Model("辣","là","hot (spicy)"));
        item.add(new HSK4Model("来不及","láibují","there's not enough time"));
        item.add(new HSK4Model("来得及","láidejí","there's still time"));
        item.add(new HSK4Model("来自","láizì","from, come from"));
        item.add(new HSK4Model("懒","lǎn","lazy"));
        item.add(new HSK4Model("浪费","làngfèi","waste"));
        item.add(new HSK4Model("浪漫","làngmàn","romantic"));
        item.add(new HSK4Model("老虎","lǎohǔ","tiger"));
        item.add(new HSK4Model("冷静","lěngjìng","calm down, cool-headed"));
        item.add(new HSK4Model("理发","lǐfà","haircut, barber, hairdressing"));
        item.add(new HSK4Model("理解","lǐjiě","understanding, comprehension"));
        item.add(new HSK4Model("理想","lǐxiǎng","ideal, perfection, desirable"));
        item.add(new HSK4Model("礼拜天","lǐbài tiān","sunday"));
        item.add(new HSK4Model("礼貌","lǐmào","courtesy, manners, politeness"));
        item.add(new HSK4Model("例如","lìrú","for example"));
        item.add(new HSK4Model("力气","lìqi","strength"));
        item.add(new HSK4Model("厉害","lìhai","great, awesome, tremendous"));
        item.add(new HSK4Model("俩","liǎ","both, some"));
        item.add(new HSK4Model("联系","liánxì","contact, connection, relation"));
        item.add(new HSK4Model("连","lián","even, repeatedly"));
        item.add(new HSK4Model("凉快","liángkuai","nice and cold, pleasantly cool"));
        item.add(new HSK4Model("零钱","língqián","small change, pocket money"));
        item.add(new HSK4Model("另外","lìngwài","in addition"));
        item.add(new HSK4Model("流利","liúlì","fluent"));
        item.add(new HSK4Model("流行","liúxíng","popular"));
        item.add(new HSK4Model("留","liú","retain, stay, keep, preserve"));
        item.add(new HSK4Model("旅行","lǚxíng","travel, trip, journey"));
        item.add(new HSK4Model("乱","luàn","chaos, disorderly"));
        item.add(new HSK4Model("律师","lǜshī","lawyer"));
        //M category
        item.add(new HSK4Model("麻烦","máfan","trouble, inconvenient"));
        item.add(new HSK4Model("马虎","mǎhu","careless"));
        item.add(new HSK4Model("满","mǎn","full, completely, satisfied"));
        item.add(new HSK4Model("毛","máo","hair, feather, wool, down"));
        item.add(new HSK4Model("毛巾","máojīn","towel"));
        item.add(new HSK4Model("美丽","měilì","beautiful, pretty"));
        item.add(new HSK4Model("梦","mèng","dream"));
        item.add(new HSK4Model("迷路","mílù","get lost"));
        item.add(new HSK4Model("密码","mìmǎ","password, secret code, pin number"));
        item.add(new HSK4Model("免费","miǎnfèi","free of charge"));
        item.add(new HSK4Model("秒","miǎo","second (of time)"));
        item.add(new HSK4Model("民族","mínzú","nationality, ethnic group"));
        item.add(new HSK4Model("母亲","mǔqīn","mother"));
        item.add(new HSK4Model("目的","mùdì","purpose, target, objective"));
        //N category
        item.add(new HSK4Model("耐心","nàixīn","patience"));
        item.add(new HSK4Model("难道","nándào","could it be that...?"));
        item.add(new HSK4Model("难受","nánshòu","uncomfortable"));
        item.add(new HSK4Model("内","nèi","inside, inner, within"));
        item.add(new HSK4Model("内容","nèiróng","content, details"));
        item.add(new HSK4Model("能力","nénglì","capability, ability"));
        item.add(new HSK4Model("年龄","niánlíng","age (a person)"));
        item.add(new HSK4Model("弄","nòng","get, make"));
        item.add(new HSK4Model("暖和","nuǎnhuo","warm"));
        //O category
        item.add(new HSK4Model("偶尔","ǒu'ěr","occasionally"));
        //P category
        item.add(new HSK4Model("排队","páiduì","queue, line up"));
        item.add(new HSK4Model("排列","páiliè","array, arrangement"));
        item.add(new HSK4Model("判断","pànduàn","judgment"));
        item.add(new HSK4Model("陪","péi","accompany"));
        item.add(new HSK4Model("批评","pīpíng","criticism"));
        item.add(new HSK4Model("皮肤","pífū","skin"));
        item.add(new HSK4Model("脾气","píqi","temperament, disposition"));
        item.add(new HSK4Model("篇","piān","piece, sheet, articles"));
        item.add(new HSK4Model("骗","piàn","to cheat, to trick, to fool"));
        item.add(new HSK4Model("乒乓球","pīngpāngqiú","table tennis"));
        item.add(new HSK4Model("平时","píngshí","peacetime, in normal times"));
        item.add(new HSK4Model("破","pò","broken, damaged"));
        item.add(new HSK4Model("葡萄","pútao","grape"));
        item.add(new HSK4Model("普遍","pǔbiàn","universal"));
        item.add(new HSK4Model("普通话","pǔtōnghuà","mandarin (Chinese language)"));
        //Q category
        item.add(new HSK4Model("其次","qícì","next, second"));
        item.add(new HSK4Model("其中","qízhōng","among"));
        item.add(new HSK4Model("气候","qìhòu","climate"));
        item.add(new HSK4Model("千万","qiānwàn","ten million"));
        item.add(new HSK4Model("签证","qiānzhèng","visa"));
        item.add(new HSK4Model("敲","qiāo","knock"));
        item.add(new HSK4Model("桥","qiáo","bridge"));
        item.add(new HSK4Model("巧克力","qiǎokèlì","chocolate"));
        item.add(new HSK4Model("亲戚","qīnqi","relative "));
        item.add(new HSK4Model("轻","qīng","light"));
        item.add(new HSK4Model("轻松","qīngsōng","easy, relaxed"));
        item.add(new HSK4Model("情况","qíngkuàng","circumstances, situation"));
        item.add(new HSK4Model("穷","qióng","poor"));
        item.add(new HSK4Model("区别","qūbié","difference, distinguish"));
        item.add(new HSK4Model("取","qǔ","take, get, choose"));
        item.add(new HSK4Model("全部","quánbù","whole, entire, complete"));
        item.add(new HSK4Model("缺点","quēdiǎn","weak point, shortcoming"));
        item.add(new HSK4Model("缺少","quēshǎo","lack, shortage"));
        item.add(new HSK4Model("却","què","but, however, yet, while"));
        item.add(new HSK4Model("确实","quèshí","indeed, really, reliable"));
        //R category
        item.add(new HSK4Model("然而","rán'ér","however, yet, but"));
        item.add(new HSK4Model("热闹","rènào","lively"));
        item.add(new HSK4Model("任何","rènhé","whatever, any"));
        item.add(new HSK4Model("任务","rènwu","task, mission, assignment"));
        item.add(new HSK4Model("扔","rēng","throw"));
        item.add(new HSK4Model("仍然","réngrán","still"));
        item.add(new HSK4Model("日记","rìjì","diary"));
        item.add(new HSK4Model("入口","rùkǒu","entrance"));
        //S category
        item.add(new HSK4Model("散步","sànbù","to go for a walk"));
        item.add(new HSK4Model("森林","sēnlín","forest"));
        item.add(new HSK4Model("沙发","shāfā","sofa"));
        item.add(new HSK4Model("伤心","shāngxīn","sad, broken-hearted"));
        item.add(new HSK4Model("商量","shāngliang","discuss, consult"));
        item.add(new HSK4Model("稍微","shāowēi","slightly, a little bit"));
        item.add(new HSK4Model("勺子","sháozi","spoon"));
        item.add(new HSK4Model("社会","shèhuì","society"));
        item.add(new HSK4Model("深","shēn","deep"));
        item.add(new HSK4Model("申请","shēnqǐng","to apply for something"));
        item.add(new HSK4Model("甚至","shènzhì","so much so that, even"));
        item.add(new HSK4Model("生活","shēnghuó","life, activity"));
        item.add(new HSK4Model("生命","shēngmìng","life, living"));
        item.add(new HSK4Model("生意","shēngyi","business"));
        item.add(new HSK4Model("省","shěng","province"));
        item.add(new HSK4Model("剩","shèng","to be left"));
        item.add(new HSK4Model("失败","shībài","fail, lose"));
        item.add(new HSK4Model("失望","shīwàng","disappointed"));
        item.add(new HSK4Model("师傅","shīfu","qualified worker, master worker"));
        item.add(new HSK4Model("十分","shífēn","very, fully, divide into ten equal parts"));
        item.add(new HSK4Model("实际","shíjì","actual, reality"));
        item.add(new HSK4Model("实在","shízài","really, honestly"));
        item.add(new HSK4Model("使","shǐ","to cause, to enable, to use"));
        item.add(new HSK4Model("使用","shǐyòng","to use"));
        item.add(new HSK4Model("世纪","shìjì","century"));
        item.add(new HSK4Model("是否","shìfǒu","whether"));
        item.add(new HSK4Model("适合","shìhé","to fit, to suit"));
        item.add(new HSK4Model("适应","shìyìng","adapt, to be suitable"));
        item.add(new HSK4Model("收","shōu","receive, accept, collect"));
        item.add(new HSK4Model("收入","shōurù","income"));
        item.add(new HSK4Model("收拾","shōushi","to put in order, pack, tidy"));
        item.add(new HSK4Model("首都","shǒudū","capital"));
        item.add(new HSK4Model("首先","shǒuxiān","in the first place"));
        item.add(new HSK4Model("受不了","shòubuliǎo","unbearable, can't stand it"));
        item.add(new HSK4Model("受到","shòudào","suffer, obtained"));
        item.add(new HSK4Model("售货员","shòuhuòyuán","salesperson"));
        item.add(new HSK4Model("输","shū","lose, fail"));
        item.add(new HSK4Model("熟悉","shúxī","be familiar with, "));
        item.add(new HSK4Model("数量","shùliàng","quantity, amount"));
        item.add(new HSK4Model("数字","shùzì","number, digit"));
        item.add(new HSK4Model("帅","shuài","handsome"));
        item.add(new HSK4Model("顺便","shùnbiàn","conveniently, Incidentally"));
        item.add(new HSK4Model("顺利","shùnlì","smoothly"));
        item.add(new HSK4Model("顺序","shùnxù","sequence, order"));
        item.add(new HSK4Model("说明","shuōmíng","explanation"));
        item.add(new HSK4Model("硕士","shuòshì","master's degree"));
        item.add(new HSK4Model("死","sǐ","dead, die, pass out"));
        item.add(new HSK4Model("塑料袋","sùliàodài","plastic bag"));
        item.add(new HSK4Model("速度","sùdù","speed, rate"));
        item.add(new HSK4Model("酸","suān","acid, sour, tart"));
        item.add(new HSK4Model("随便","suíbiàn","as one wishes, casual"));
        item.add(new HSK4Model("随着","suízhe","along with"));
        item.add(new HSK4Model("孙子","sūnzi","grandson (paternal)"));
        item.add(new HSK4Model("所有","suǒyǒu","all"));
        //T category
        item.add(new HSK4Model("台","tái","platform, station, classifier for vehicles or machines"));
        item.add(new HSK4Model("抬","tái","to lift, to raise, to carry"));
        item.add(new HSK4Model("态度","tàidu","attitude, manner, approach"));
        item.add(new HSK4Model("弹钢琴","tángāngqín","play the piano"));
        item.add(new HSK4Model("谈","tán","chat, discuss, talk"));
        item.add(new HSK4Model("汤","tāng","soup, hot water"));
        item.add(new HSK4Model("糖","táng","sugar, sweets, candy"));
        item.add(new HSK4Model("躺","tǎng","lie, to recline"));
        item.add(new HSK4Model("趟","tàng","quantifier for the number of trips or runs made"));
        item.add(new HSK4Model("讨论","tǎolùn","to talk over, to discuss"));
        item.add(new HSK4Model("讨厌","tǎoyàn","hate, dislike, annoying"));
        item.add(new HSK4Model("特点","tèdiǎn","characteristic, feature"));
        item.add(new HSK4Model("提","tí","to carry, to lift, to raise"));
        item.add(new HSK4Model("提供","tígōng","supply, provide"));
        item.add(new HSK4Model("提前","tíqián","in advance"));
        item.add(new HSK4Model("提醒","tíxǐng","remind"));
        item.add(new HSK4Model("填空","tiánkòng","fill in the blanks"));
        item.add(new HSK4Model("条件","tiáojiàn","condition, requirement"));
        item.add(new HSK4Model("停","tíng","stop, halt"));
        item.add(new HSK4Model("挺","tǐng","very, extraordinary, outstanding, classifier for machine guns"));
        item.add(new HSK4Model("通过","tōngguò","through"));
        item.add(new HSK4Model("通知","tōngzhī","notice, notification"));
        item.add(new HSK4Model("同情","tóngqíng","sympathy"));
        item.add(new HSK4Model("同时","tóngshí","simultaneously, at the same time"));
        item.add(new HSK4Model("推","tuī","push"));
        item.add(new HSK4Model("推迟","tuīchí","delay, postpone"));
        item.add(new HSK4Model("脱","tuō","take off, get away from"));
        //W category
        item.add(new HSK4Model("袜子","wàzi","socks"));
        item.add(new HSK4Model("完全","wánquán","completely, entirely"));
        item.add(new HSK4Model("往往","wǎngwǎng","often, frequently"));
        item.add(new HSK4Model("网球","wǎngqiú","tennis"));
        item.add(new HSK4Model("网站","wǎngzhàn","website, network station"));
        item.add(new HSK4Model("危险","wēixiǎn","dangerous"));
        item.add(new HSK4Model("卫生间","wèishēngjiān","bathroom, toilet"));
        item.add(new HSK4Model("味道","wèidào","taste, flavor, smell"));
        item.add(new HSK4Model("温度","wēndù","temperature"));
        item.add(new HSK4Model("文章","wénzhāng","article, essay"));
        item.add(new HSK4Model("污染","wūrǎn","pollution, contamination"));
        item.add(new HSK4Model("无","wú","nothing"));
        item.add(new HSK4Model("无聊","wúliáo","boring"));
        item.add(new HSK4Model("无论","wúlùn","no matter what"));
        item.add(new HSK4Model("误会","wùhuì","misunderstand, mistake"));
        //X category
        item.add(new HSK4Model("吸引","xīyǐn","to attract (interest, investment etc)"));
        item.add(new HSK4Model("西红柿","xīhóngshì","tomato"));
        item.add(new HSK4Model("咸","xián","salty"));
        item.add(new HSK4Model("现金","xiànjīn","cash"));
        item.add(new HSK4Model("羡慕","xiànmù","envious, envy"));
        item.add(new HSK4Model("相反","xiāngfǎn","opposite, contrary"));
        item.add(new HSK4Model("相同","xiāngtóng","same, identical"));
        item.add(new HSK4Model("香","xiāng","fragrant, sweet smelling"));
        item.add(new HSK4Model("详细","xiángxì","detailed"));
        item.add(new HSK4Model("响","xiǎng","ring, classifier for noises"));
        item.add(new HSK4Model("橡皮","xiàngpí","rubber, eraser"));
        item.add(new HSK4Model("消息","xiāoxi","news, information"));
        item.add(new HSK4Model("小吃","xiǎochī","snack"));
        item.add(new HSK4Model("小伙子","xiǎohuǒzi","young man, young fellow"));
        item.add(new HSK4Model("小说","xiǎoshuō","novel, fiction"));
        item.add(new HSK4Model("效果","xiàoguǒ","result, effect"));
        item.add(new HSK4Model("笑话","xiàohua","joke"));
        item.add(new HSK4Model("心情","xīnqíng","mood, frame of mind"));
        item.add(new HSK4Model("辛苦","xīnkǔ","hard, exhausting"));
        item.add(new HSK4Model("信封","xìnfēng","envelope"));
        item.add(new HSK4Model("信息","xìnxī","information"));
        item.add(new HSK4Model("信心","xìnxīn","confidence, faith"));
        item.add(new HSK4Model("兴奋","xīngfèn","excitement"));
        item.add(new HSK4Model("行","xíng","row, travel, all right"));
        item.add(new HSK4Model("醒","xǐng","wake up"));
        item.add(new HSK4Model("幸福","xìngfú","happiness"));
        item.add(new HSK4Model("性别","xìngbié","gender, sex"));
        item.add(new HSK4Model("性格","xìnggé","character, temperament"));
        item.add(new HSK4Model("修理","shūri","repair, maintenance"));
        item.add(new HSK4Model("许多","xǔduō","many, much, lot of"));
        item.add(new HSK4Model("学期","xuéqí","semester, school term"));
        //Y category
        item.add(new HSK4Model("呀","ya","ahh!, expressing surprise or doubt"));
        item.add(new HSK4Model("压力","yālì","pressure"));
        item.add(new HSK4Model("牙膏","yágāo","toothpaste"));
        item.add(new HSK4Model("亚洲","yàzhōu","asia"));
        item.add(new HSK4Model("严格","yángé","strict, tight"));
        item.add(new HSK4Model("严重","yánzhòng","serious, critical"));
        item.add(new HSK4Model("盐","yán","salt"));
        item.add(new HSK4Model("研究","yánjiūshēng","graduate student"));
        item.add(new HSK4Model("演出","yǎnchū","to perform, to show, to act (in a play)"));
        item.add(new HSK4Model("演员","yǎnyuán","actor or actress"));
        item.add(new HSK4Model("眼镜","yǎnjìng","eyeglasses"));
        item.add(new HSK4Model("阳光","yángguāng","sunshine, sunlight"));
        item.add(new HSK4Model("养成","yǎngchéng","cultivate, acquire"));
        item.add(new HSK4Model("样子","yàngzi","looks, appearance"));
        item.add(new HSK4Model("邀请","yāoqǐng","invitation"));
        item.add(new HSK4Model("要是","yàoshi","if"));
        item.add(new HSK4Model("钥匙","yàoshi","key"));
        item.add(new HSK4Model("也许","yěxǔ","perhaps, maybe, probably"));
        item.add(new HSK4Model("叶子","yèzi","leaf, foliage"));
        item.add(new HSK4Model("页","yè","page"));
        item.add(new HSK4Model("一切","yíqiè","all, everything"));
        item.add(new HSK4Model("以","yǐ","with, to use as, according to"));
        item.add(new HSK4Model("以为","yǐwéi","think, believe, consider"));
        item.add(new HSK4Model("意见","yìjiàn","opinion, suggestion, objection"));
        item.add(new HSK4Model("艺术","yìshù","art"));
        item.add(new HSK4Model("因此","yīncǐ","consequently, therefore"));
        item.add(new HSK4Model("引起","yǐnqǐ","to give rise, cause"));
        item.add(new HSK4Model("印象","yìnxiàng","impression, reflection"));
        item.add(new HSK4Model("赢","yíng","win, beat"));
        item.add(new HSK4Model("应聘","yìngpìn","to apply for position"));
        item.add(new HSK4Model("勇敢","yǒnggǎn","brave, courageous"));
        item.add(new HSK4Model("永远","yǒngyuǎn","forever, eternal"));
        item.add(new HSK4Model("优点","yōudiǎn","advantage, benefit"));
        item.add(new HSK4Model("优秀","yōuxiù","excellent, outstanding"));
        item.add(new HSK4Model("幽默","yōumò","humor"));
        item.add(new HSK4Model("尤其","yóuqí","especially, particularly"));
        item.add(new HSK4Model("由","yóu","from, to follow"));
        item.add(new HSK4Model("由于","yóuyú","due to, because of"));
        item.add(new HSK4Model("邮局","yóujú","post Office"));
        item.add(new HSK4Model("友好","yǒuhǎo","friendly"));
        item.add(new HSK4Model("友谊","yǒuyì","friendship, fellowship"));
        item.add(new HSK4Model("有趣","yǒuqù","interesting, fascinating"));
        item.add(new HSK4Model("于是","yúshì","then, consequently"));
        item.add(new HSK4Model("愉快","yúkuài","cheerful, delightful, pleasant"));
        item.add(new HSK4Model("与","yǔ","versus, and"));
        item.add(new HSK4Model("羽毛球","yǔmáoqiú","badminton, shuttlecock"));
        item.add(new HSK4Model("语法","yǔfǎ","grammar"));
        item.add(new HSK4Model("语言","yǔyán","language"));
        item.add(new HSK4Model("预习","yùxí","to prepare a lesson"));
        item.add(new HSK4Model("原来","yuánlái","original"));
        item.add(new HSK4Model("原谅","yuánliàng","forgive"));
        item.add(new HSK4Model("原因","yuányīn","reason, cause, origin"));
        item.add(new HSK4Model("约会","yuēhuì","appointment, engagement, date"));
        item.add(new HSK4Model("阅读","yuèdú","read"));
        item.add(new HSK4Model("云","yún","cloud"));
        item.add(new HSK4Model("允许","yǔnxǔ","allow, permit"));
        //Z category
        item.add(new HSK4Model("杂志","zázhì","magazine"));
        item.add(new HSK4Model("咱们","zánmen","we or us(including both speaker and person spoken to)"));
        item.add(new HSK4Model("暂时","zànshí","temporary"));
        item.add(new HSK4Model("脏","zāng","dirty"));
        item.add(new HSK4Model("责任","zérèn","responsibility, duty"));
        item.add(new HSK4Model("增加","zēngjiā","increase"));
        item.add(new HSK4Model("占线","zhànxiàn","busy (telephone)"));
        item.add(new HSK4Model("招聘","zhāopìn","recruitment, to invite applications for a job"));
        item.add(new HSK4Model("照","zhào","according to"));
        item.add(new HSK4Model("真正","zhēnzhèng","genuine, real"));
        item.add(new HSK4Model("整理","zhěnglǐ","arrangement"));
        item.add(new HSK4Model("正常","zhèngcháng","normal, regular"));
        item.add(new HSK4Model("正好","zhènghǎo","just right, just enough"));
        item.add(new HSK4Model("正确","zhèngquè","correct, proper"));
        item.add(new HSK4Model("正式","zhèngshì","formal, official"));
        item.add(new HSK4Model("证明","zhèngmíng","prove, certificate, identification"));
        item.add(new HSK4Model("之","zhī","of"));
        item.add(new HSK4Model("支持","zhīchí","support, sustain"));
        item.add(new HSK4Model("知识","zhīshi","knowledge, intellectual"));
        item.add(new HSK4Model("值得","zhídé","worth"));
        item.add(new HSK4Model("植物","zhíwù","plant, botanical"));
        item.add(new HSK4Model("直接","zhíjiē","direct, straightforward"));
        item.add(new HSK4Model("职业","zhíyè","occupation, profession"));
        item.add(new HSK4Model("只好","zhǐhǎo","have to, without any better option"));
        item.add(new HSK4Model("只要","zhǐyào","as long as"));
        item.add(new HSK4Model("指","zhǐ","finger, to point"));
        item.add(new HSK4Model("至少","zhìshǎo","at least"));
        item.add(new HSK4Model("质量","zhìliàng","quality"));
        item.add(new HSK4Model("重","zhòng","weight, heavy"));
        item.add(new HSK4Model("重点","zhòngdiǎn","focal point, priority, key"));
        item.add(new HSK4Model("重视","zhòngshì","to attach importance to something"));
        item.add(new HSK4Model("周围","zhōuwéi","surroundings, environment"));
        item.add(new HSK4Model("主意","zhǔyi","idea, plan"));
        item.add(new HSK4Model("祝贺","zhùhè","congratulations"));
        item.add(new HSK4Model("著名","zhùmíng","famous, well-known"));
        item.add(new HSK4Model("专门","zhuānmén","specialist, specialized"));
        item.add(new HSK4Model("专业","zhuānyè","major, specialty, main field of study"));
        item.add(new HSK4Model("转","zhuǎn","to turn, to change direction, to transfer"));
        item.add(new HSK4Model("赚","zhuàn","earn, make a profit"));
        item.add(new HSK4Model("准确","zhǔnquè","accuracy, exact"));
        item.add(new HSK4Model("准时","zhǔnshí","on time, punctual"));
        item.add(new HSK4Model("仔细","zǐxì","careful, attentive"));
        item.add(new HSK4Model("自然","zìrán","natural, free from affectation"));
        item.add(new HSK4Model("自信","zìxìn","self-confidence"));
        item.add(new HSK4Model("总结","zǒngjié","summary, conclude"));
        item.add(new HSK4Model("租","zū","rent, hire"));
        item.add(new HSK4Model("最好","zuìhǎo","best"));
        item.add(new HSK4Model("尊重","zūnzhòng","respect, honor"));
        item.add(new HSK4Model("左右","zuǒyòu","approximately, about, left and right"));
        item.add(new HSK4Model("作家","zuòjiā","writer, author"));
        item.add(new HSK4Model("作用","zuòyòng","affect, action, impact"));
        item.add(new HSK4Model("作者","zuòzhě","writer, author"));
        item.add(new HSK4Model("座","zuò","seat, base, (classifier for buildings, mountains)"));
        item.add(new HSK4Model("座位","zuòwèi","a place to sit"));



        hsk4Adapter = new HSK4Adapter(this, R.layout.hsk4_listview_row, item);
        listView.setAdapter(hsk4Adapter);
    }
}